CONSTANTE_VELOCIDADE_GERADOR_V_RAD_S = 1.55
RESISTENCIA_ARMADURA_OHMS = 0.45
INDUTANCIA_ARMADURA_HENRIES = 8.5e-3
INERCIA_GERADOR_KG_M2 = 0.10
COEFICIENTE_ATRITO_GERADOR = 0.015

RAIO_TURBINA_METROS = 2.5
INERCIA_TURBINA_KG_M2 = 0.10
COEFICIENTE_ATRITO_TURBINA = 0.01
RELACAO_TRANSMISSAO_CAIXA_ENGRENAGENS = 4
INCREMENTO_VELOCIDADE_ANG_SOFTSTART_SIMULACAO_RAD_S = 0.045
VELOCIDADE_EIXO_FIM_SOFT_START_PERC_ALVO = 0.8
CONSTANTE_TEMPO_FILTRO_VELOCIDADE_ALVO = 0.5

TORQUE_MAXIMO_MOTOR_NM = 79.63
TAXA_VARIACAO_TENSAO_ARMADURA_V_S = 100.0
VELOCIDADE_MAXIMA_PAS_GRAUS_S = 5.0
TENSAO_MAXIMA_INVERSOR_V = 300
TENSAO_MINIMA_INVERSOR_V = 0

VELOCIDADE_VENTO_MINIMA_M_S = 2.2
TSR_IDEAL = 9.5
POTENCIA_MECANICA_MAXIMA_W = 2000

PASSO_SIMULACAO_SEGUNDOS = 0.02
PASSO_HARDWARE_SEGUNDOS = 0.001
TEMPO_TOTAL_EMULACAO_SEGUNDOS = 60*3
TAXA_ATUALIZACAO_GRAFICOS_SEGUNDOS = 1.0

INCREMENTO_VELOCIDADE_ANG_SOFT_START_EIXO_RPM = 1.5
POTENCIA_EIXO_FIM_SOFT_START_W = 10.0
CONSTANTE_TEMPO_FILTRO_SENSOR_POTENCIA = 0.1
CONSTANTE_TEMPO_FILTRO_SENSOR_VELOCIDADE = 0.1

#PERFIL_VENTO = 'ESCADA' 
PERFIL_VENTO = 'NATURAL'
from numpy import load
VETOR_VENTO_M_S = load('vetor_vento.npy')
